### ISSUE TITLE
epic: Program Component

### ISSUE THREAD

**Issue by zmalatrax** [kkrt-labs/stwo-brainfuck#122]
In order to prove that the Instruction table is effectively a sublist (ordered subset) of the program (`ProgramMemory`) that was run by the `brainfuck_vm`, we actually need a component representing the program itself (to use the LogUp protocol).

No need to add local constraints to the Program component, simply on the logUp column shared with the Instruction component.
As there is no local constraints, no need to flatten two consecutives rows (i.e. entries) into a single row as in the Instruction component. 

Note: Should we enforce a sorting on `ip`, and add constraints that `ip` increases by one, starting at 0? Adding a constraint that `ip` must always be increased by one allows for the uniqueness of `ip` (unless it's a dummy row)

# Trace

| ip | ci | ni | d |
| --- | --- | --- | --- |
```[tasklist]
### Trace
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/151
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/152
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/153
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/154
```

```[tasklist]
### Interaction Trace
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/155
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/156
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/157
```

```[tasklist]
### Component
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/158
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/159
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/160
```
