### ISSUE TITLE
epic: Instruction component

### ISSUE THREAD

**Issue by zmalatrax** [kkrt-labs/stwo-brainfuck#16]
## What needs to be done?

- Produce the main trace (interaction phase 1)
  - Cherry-picking columns from the execution trace
  - Sort by instruction pointer `ip`
- Produce the interaction trace (interaction phase 2)
- Is there a need for constant columns? (interaction phase 0) - **Yes**, $`\text{is\_first}`$ to apply boundary constraints
- Claim on log sizes and InteractionClaim on LogUp claimed sum
- Implement the `FrameworkEval` and derive the component from `FrameworkComponent`: `InstructionComponent`
  - Especially the `evalutate` function (defining all the constraints linked to this component)

## Trace

**UPDATE**: The design of Stwo makes it easier to evaluate transition constraints on a single row, thus having the $i$ and  $i + 1$ value on the same row of the component ; rather than doing bit-reversals to obtain the neighboring row (+ much cheaper, we don't have much columns).

Sorted by `ip`.

|  ip  |  ci  |  ni  |  next_ip  |  next_ci  |  next_ni  |
| --- | --- | --- | --- | --- | --- |
| Instruction Pointer | Current Instruction | Next Instruction | Next Instruction Pointer | Next Current Instruction | Next Next Instruction |

This way, in the constraints defined below $`ip_i`$ would be `ip` and $`ip_{i+1}`$ would be `next_ip`.

## Constraints

Constraints taken from the [BrainSTARK project](https://aszepieniec.github.io/stark-brainfuck/arithmetization)

- 1 boundary constraint (interaction phase 0)
- ~4~ 3 transition constraints (interaction phase 0)
- 1 permutation argument with the Processor Component (interaction phase 1)
- 1 evaluation argument with the Program (interaction phase 1)
- 2 terminal constraints (Interaction phase 1) *Necessary?*

| Constraint Description | Polynomial | Type |
| --- | --- | --- |
| The register `ip` starts at 0 | $`\text{is\_first} \cdot ip= 0`$ | Boundary |
| `ip` increases by 0 or 1 | $`({ip}_{i+1} - {ip}_i) \cdot ({ip}_{i+1} - {ip}_i - 1) = 0`$ | Transition | 
| If `ip` remains the same, so does `ci` | $`({ip}_{i+1} - {ip}_i - 1) \cdot ({ci}_{i+1} - {ci}_i) = 0`$ | Transition
| If `ip` remains the same, so does `ni` | $`({ip}_{i+1} - {ip}_i - 1) \cdot ({ni}_{i+1} - {ni}_i) = 0`$ | Transition
| ~If `ip` increases by 1, the current `ni` must equal the next `ci`~ | $`({ip}_{i+1} - {ip}_i) \cdot ({ni}_{i} - {ci}_{i+1}) = 0`$ | ~Transition~ (redundant)
| Permutation argument with Processor component : Accumulates only if not a padded row and `ip` remains the same. | $`{ci}_i \cdot ({ip}_{i+1} - {ip}_i - 1) \cdot ({ppa} \cdot \text{combine}({ip}_i, {ci}_i, {ni}_i) - {ppa}_{i+1}) + \text{zeroifier(ci)} \cdot ({ppa}_{i+1} - {ppa}_i - 1) + ({ip}_{i+1} - {ip}_i - 1) \cdot ({ppa}_i - {ppa}_{i+1})`$ | Permutation
| Evaluation argument with Processor component: Accumulates when `ip` changes, remains the same otherwise | $`({ip}_{i+1} - {ip}_i - 1) \cdot ({pea}_i - {pea}_{i+1}) + ({ip}_{i+1} - {ip}_i) \cdot \text{combine}({ip}_i, {ci}_i, {ni}_i) - {pea}_{i+1}`$ | Evaluation
| The Processor Permutation Argument has accumulated all rows | $`{ppa}_{final} - T_{ppa} = 0`$ | Terminal
| The Processor Evaluation Argument has accumulated all rows | $`{pea}_{final} - T_{pea} = 0`$ | Terminal

In the [article ](https://aszepieniec.github.io/stark-brainfuck/arithmetization#instruction-table )the three polynomials of the processor permutation argument (ppa) have been written the other way round compared to the other polynomials of the AIR (i+1 - i rather than i - i+1).
Also, they use the i+1-th term for the register combination rather the current column i, why should it be different, as this argument should equal to the Instruction Permutation Argument (ipa) in the Processor component (which is described with i-th terms)? 

The $`\text{combine}(x, y)`$ function draws random coefficients from the channel and makes a linear combination of the given arguments: $`\alpha \cdot x + \beta \cdot y`$
```[tasklist]
### Main Trace
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/29
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/30
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/31
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/53
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/56
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/109
```

```[tasklist]
### Interaction Trace
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/119
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/120
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/121
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/148
```

```[tasklist]
### Component
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/125
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/150
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/149
```
