### ISSUE TITLE
epic: Memory Component

### ISSUE THREAD

**Issue by zmalatrax** [kkrt-labs/stwo-brainfuck#3]
## What needs to be done?

- Produce the main trace (interaction phase 1)
  - Cherry-picking columns from the execution trace
  - Sort by memory pointer `mp` then cycle `clk`
- Produce the interaction trace (interaction phase 2)
- Is there a need for constant columns? (interaction phase 0) - **Yes**, $`\text{is\_first}`$ to apply boundary constraints
- Is there a need for Statement? **To Be Determined (TBD)**
- Implement the `FrameworkEval` and derive the Components from `FrameworkComponent`: `MemoryComponent`
  - Especially the `evalutate` function (defining all the constraints linked to this component)

## Trace

Update: The design of Stwo makes it easier to evaluate transition constraints on a single row, thus having the $i$ and ${i+1}$ value on the same row of the component ; rather than doing bit-reversals to obtain the neighboring row (+ much cheaper, we don't have much columns).

Sorted by `mp` and then by `clk`.

| clk | mp | mv | d | next_clk | next_mp | next_mv | next_d |
| --- | --- | --- | ---|  --- | --- | --- | ---| 
| Clock Cycle Counter | Memory Pointer | Memory Value | Dummy, for contiguous memory (see Constraints) | Next Clock Cycle Counter | Next Memory Pointer | Next Memory Value | Next Dummy

This way, in the constraints defined below $`clk_i`$ would be `clk` and $`clk_{i+1}`$ would be `next_clk`.

## Constraints

Constraints taken from the BrainSTARK project

To mitigate an attack on the proof generation, the initial constraints on the memory described [here](https://aszepieniec.github.io/stark-brainfuck/arithmetization) are replaced by [these ones](https://aszepieniec.github.io/stark-brainfuck/attack).
The goal is to enforce the correct ordering of the trace.
Proposed solution makes the memory contiguous (a single segment), as in the relocated Cairo memory, while adding a column to flag whether the memory row is dummy or not. It is said that the design space is large to overcome this attack, following their mitigation is the most pragmatic choice, there might be better design though.

- 4 boundary constraint (interaction phase 0)
- 6 transition constraints (interaction phase 0)
- 1 permutation argument with the Processor Component (interaction phase 1)
- 1 terminal constraint (Interaction phase 1) *Necessary?*

| Constraint Description | Polynomial | Type |
| --- | --- | --- |
| The register `clk` starts at 0 | $`\text{is\_first} \cdot clk = 0`$ | Boundary |
| The register  `mp` starts at 0 | $`\text{is\_first} \cdot mp = 0`$ | Boundary |
| The register  `mv` starts at 0 | $`\text{is\_first} \cdot mv = 0`$ | Boundary |
| The register  `d` starts at 0 | $`\text{is\_first} \cdot d = 0`$ | Boundary |
| Memory pointer `mp` increases by 0 or 1 | $`({mp}_{i+1} - {mp}_i) \cdot ({mp}_{i+1} - {mp}_i - 1) = 0`$ | Transition | 
| If `mp` remains the same, the clock cycle counter increases by 1 | $`({mp}_{i+1} - {mp}_i - 1) \cdot ({clk}_{i+1} - {clk}_i - 1) = 0`$ | Transition
| If `mp` increases by 1, then new `mv` must be 0 | $`({mp}_{i+1} - {mp}_i) \cdot {mv}_{i+1} = 0`$ | Transition | 
| The next dummy `d`is either 0 or 1 | $`d_{i+1} \cdot (d_{i+1} - 1) = 0`$ | Transition
| If `d` is set, `mv` remains the same | $`d \cdot ({mv}_{i+1} - {mv}_i) = 0`$ | Transition | 
| Id `d` is set, `mp` remains the same | $`d_i \cdot ({mp}_{i+1} - {mp}_i) = 0`$ | Transition |
| Running product "ppa" of `clk`, `mp` and `mv` only if `d` is not set | $`d_i \cdot {ppa}_i + (1 - d_i) \cdot {ppa}_i \cdot \text{combine}({clk}_i, {mp}_i, {mv}_i) - {ppa}_{i+1} = 0`$ | Permutation
| The running product has accumulated all rows but the last | $`d_i \cdot {ppa}_i + (1 - d_i) \cdot {ppa}_i \cdot \text{combine}({clk}_i, {mp}_i, {mv}_i) - T_{ppa} = 0`$ | Terminal

As the memory trace is a permutation of the Processor component, the boundary constraints could be applied only to the Processor component and verified by the permutation argument that links them. (Is it still the case with the introduction of the dummy column?)

The $`\text{combine}(x, y)`$ function draws random coefficients from the channel and makes a linear combination of the given arguments: $`\alpha \cdot x + \beta \cdot y`$
```[tasklist]
### Main Trace
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/32
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/33
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/34
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/43
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/52
- [ ] #55
- [x] refactor: refactor MemoryTable to flatten evaluation of transition constraints
```

```[tasklist]
### Interaction Trace
- [x] Design the lookup for Memory component
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/89
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/90
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/92
```

```[tasklist]
### Component
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/98
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/101
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/102
```

```[tasklist]
### Preprocessed trace
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/100
```
