### ISSUE TITLE
epic: I/O Component

### ISSUE THREAD

**Issue by zmalatrax** [kkrt-labs/stwo-brainfuck#41]
> The Input Table and the Output Table are analogous; both are specializations of a more general I/O Table.
The difference between both tables is the value they are populated with, and the challenge used.
Therefore, we should make an I/O Component and define the Input and Output tables out of it

## What needs to be done?

- Produce the main trace (interaction phase 1)
  - Cherry-pick column from the execution trace: `mv` when current instruction is `,` or `.`
- Produce the interaction trace (interaction phase 2)
- Is there a need for constant columns? (interaction phase 0) - **Yes**, $`\text{is\_first}`$ to apply boundary constraints
- Statements, also called Claim and InteractionClaim (on the columns log sizes, and on the LogUp claimed sum).
- Implement the `FrameworkEval` and derive the component from `FrameworkComponent`: `IOComponent`
  - Especially the `evalutate` function (defining all the constraints linked to this component)

## Trace

Only constituted of `mv` (when the instruction is ',' for input or '.' for output?!)

|  mv  |
| --- |
| Memory Value |

## Constraints

Constraints taken from the [BrainSTARK project](https://aszepieniec.github.io/stark-brainfuck/arithmetization)

Here, the constraints only applies to the extension column (interaction phase 1), which is an evaluation argument of the base column.

- 1 boundary constraint (interaction phase 1)
- 1 evaluation argument (interaction phase 1)
- 1 terminal constraint (Interaction phase 1) *Necessary?*

| Constraint Description | Polynomial | Type |
| --- | --- | --- |
| The running sum starts with the initial value of first `mv` value in the table | $`\text{is\_first} \cdot {ea} - {mv}_0 = 0`$ | Boundary |
| Evaluation argument: Accumulates `mv` on each row | $`\text{combine}({ea}_i) + {mv}_{i+1}- {ea}_{i+1}`$ | Transition/Evaluation
| The Evaluation Argument has accumulated all rows | $`{ea}_{final} - T_{ea} = 0`$ | Terminal

The $`\text{combine}(x, y)`$ function draws random coefficients from the channel and makes a linear combination of the given arguments: $`\alpha \cdot x + \beta \cdot y`$

```[tasklist]
### Main Trace
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/46
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/47
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/54
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/57
```

```[tasklist]
### Interaction Trace
- [ ] Design the lookup for I/O component
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/117
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/118
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/138
```

```[tasklist]
### Component
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/124
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/139
- [ ] https://github.com/kkrt-labs/stwo-brainfuck/issues/142
```
